name: Mirror repo to S3
on:
  push:
    branches:
      - main
env:
  BUCKET_NAME : "mate-github"
  AWS_REGION : "eu-central-1"
jobs:
  s3Backup:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::781122033386:role/sync-learn-repo-to-s3
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Find updated files in git
        shell: bash
        run: |
          FILES=()
          for i in $( git diff --name-only HEAD HEAD~1); do
              FILES+=( "$i" )
          done
          echo "${FILES[@]}"
      - name: Copy files to the s3 mate-github bucket
        run:
          aws s3 sync --size-only . s3://${{ env.BUCKET_NAME }}/learn
